version: '3.8'
services:
  # server:
  #   build:
  #     context: ./
  #     target: development-build-stage
  #     dockerfile: Dockerfile
  #   container_name: server2
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #     - '5555:5555'
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

  # links:
  #   - 'postgres:postgres'
  # depends_on:
  #   - postgres

  backend:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:app
      - /app/node_modules
      - /app/prisma
  postgres:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: prisma
    volumes:
      - postgres-data:/var/lib/postgresql/data

    restart: unless-stopped

  prisma:
    image: prismagraphql/prisma:1.26
    depends_on:
      - postgres
    links:
      - postgres
    container_name: prisma
    restart: always
    ports:
      - '5555:5555'
    build:
      context: prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma

  # prisma-postgres-api:
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: prisma-postgres-api
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #   restart: always

volumes:
  postgres-data:
