version: '3'
services:
  dev-db:
    image: postgres:12
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jozveh
  test-db:
    image: postgres:12
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jozveh-test-db
