version: '3.8'
services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend
    links:
      - "psql:postgres"
    depends_on:
      - psql
      
  psql:
    image: postgres:15.1-alpine3.17
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
