version: "3.8"

networks:
  default:
    name: web_net

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - default
